//@baseUrl=https://sheltered-beach-83949.herokuapp.com/
@nodeProdUrl=https://moln-node.azurewebsites.net
@nodeUrl=http://localhost:3000
@baseUrl=http://127.0.0.1:5000

###
GET {{nodeProdUrl}}

###login
POST {{nodeProdUrl}}/users/login
Content-Type: application/json

{
    "email": "tommyshelby@doe.com",
    "password": "Password123"
}

###
POST {{baseUrl}}
Content-Type: application/json

{
    "username": "jimhalpert",
    "email": "jim@office.com"
}

###TEST
GET {{baseUrl}}/cabins

###SERVICES
GET {{baseUrl}}/services

###
POST {{baseUrl}}/services
Content-Type: application/json

{
    "service": "lawn mowing"
}

###
PUT {{baseUrl}}/services/3
Content-Type: application/json

{
    "service" : "roof cleaning"
}

###
DELETE {{baseUrl}}/services/4

###ORDERS
GET {{baseUrl}}/orders

###
POST {{baseUrl}}/orders
Content-Type: application/json

{
    "service": "roof cleaning",
    "cabin_id": "6155798243d4392e67def2ee",
    "date": "2021-10-12"
}

###
PUT {{baseUrl}}/orders/4
Content-Type: application/json

{
    "service" : "roof cleaning",
    "date": ""
}

###
DELETE {{baseUrl}}/orders/6
